Feat/main page
DonGrafon23/aviasales-demo-frontend pull request #1
Opened 2018-07-09 18:33 UTC by DonGrafon23

I did the part with the tickets, after I finish the main page I will divide the code into parts. I conditionally divided the code into parts for convenience by comments.

2018-07-11 21:02 UTC, evgenyrodionov commented
а можно не кидать проверку на 49 файла?

2018-07-11 21:04 UTC, evgenyrodionov commented
От таких гигантских пуллреквестов смысла нет, их невозможно проверять качественно: вместо условных 10 файлов которым можно уделить всё внимание, проверяющий проебётся во многих деталях

Не делай так никогда больше

2018-07-11 21:37 UTC, imevro requested changes
даже проверять нечего

2018-07-11 21:37 UTC, evgenyrodionov commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
зачем все стили грузить?

2018-07-11 21:37 UTC, evgenyrodionov commented on src/App.css
> +     position: absolute;
что со стилем? почему всё так скачет? где два пробела в отступах?

2018-07-11 21:37 UTC, evgenyrodionov commented on src/App.js
> +export default Main;
с файлом на 2237 строчек удобно работать? разделяй

2018-07-11 21:37 UTC, evgenyrodionov commented on src/img/airLine.min.svg
> +<image id="image0" width="56" height="56" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAA4CAYAAACohjseAAAAAXNSR0IArs4c6QAAClBJREFUaAXNmn1s1dUZx/tC0Y53KeDQQnl/cUyjgMvYTHzJ0Ghc5pJt7kV
зачем ты пнг засунул в свг?

2020-09-28 09:42 UTC, DonGrafon23 commented
> даже проверять нечего

2020-09-28 09:42 UTC, closed without merging